// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qwerty.Data;

namespace qwerty.Migrations
{
    [DbContext(typeof(qwertyContext))]
    [Migration("20210514193417_clcl")]
    partial class clcl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("school.models.Class", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bukva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("God_obuchenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("God_sozdania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kolichestvo_uchenikov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("sotrudnikiID")
                        .HasColumnType("bigint");

                    b.Property<long?>("vidID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("school.models.Dolznost", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naimenovanie_dolznosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obazannosty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oklad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trebovania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("sotrudnikiID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("sotrudnikiID");

                    b.ToTable("Dolznost");
                });

            modelBuilder.Entity("school.models.sotrudniki", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ClassID")
                        .HasColumnType("bigint");

                    b.Property<long?>("DolznostID")
                        .HasColumnType("bigint");

                    b.Property<string>("FIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Old")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pasport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("sotrudniki");
                });

            modelBuilder.Entity("school.models.vid", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ClassID")
                        .HasColumnType("bigint");

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opisanie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.ToTable("vid");
                });

            modelBuilder.Entity("school.models.Dolznost", b =>
                {
                    b.HasOne("school.models.sotrudniki", null)
                        .WithMany("Dolznost")
                        .HasForeignKey("sotrudnikiID");
                });

            modelBuilder.Entity("school.models.sotrudniki", b =>
                {
                    b.HasOne("school.models.Class", null)
                        .WithMany("sotrudniki")
                        .HasForeignKey("ClassID");
                });

            modelBuilder.Entity("school.models.vid", b =>
                {
                    b.HasOne("school.models.Class", null)
                        .WithMany("vid")
                        .HasForeignKey("ClassID");
                });

            modelBuilder.Entity("school.models.Class", b =>
                {
                    b.Navigation("sotrudniki");

                    b.Navigation("vid");
                });

            modelBuilder.Entity("school.models.sotrudniki", b =>
                {
                    b.Navigation("Dolznost");
                });
#pragma warning restore 612, 618
        }
    }
}
